version: '3'

services:
  app:
    build: .
    command: bin/rails server -b 0.0.0.0
    env_file: .env
    environment:
      DATABASE_URL: "postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}"
      PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAxR+Q3c+iBlKhcyd0mcgRkyHpRx8NdPW5agUeUenwrC8YyQIb\nshumV4w/gJZ+qGw7g3VXkXe+fAUhV9c+XiXzg0ouNCVbg5lT0Wr+PmkOM/bAGLHp\ny5pZ2RaFKzKLB1shZoMXpoR/LlK6j7mli0TsWzwwq46L8CV+UiN6mnKazwF6mFyL\nQUaZ8qbcKHYYh500y33SmtncELlyuNPOGrmu3wOUjmfwfC0rTPb0XaxC2yMfMDmc\nfGXwYZliLgi9521P3yQm9dHjbo/ML99cYA3yQFP211ZXdO6esup1Z6sOsxw95t6U\n6AjU3cXcC03NohhSK9DmOp0aSzGdeUEdvTTkmwIDAQABAoIBACAAz/QzEYsVP0EC\n1ttgr/nDN6xkTjr+6etciV+jK3/I5a08umJgOtFb47Nsu4N8juz40A698h8Qdilc\nuLNwVeiq0nWE2yaybflB9aUMSVIGbYmU2PBFTvD/xv8MZaX8FaAfCGfwevV6WO+c\npFPIDNeDHiO8MNv8OlX7jJwmnxucSN3eeVbobql87IVzz2TrXOnIPcgD+5pwhZT9\nbUeYj4kfCfXvESNWqqhW9faSaFRwVaJmLNx9lPVXjPsbyWddrTzQWZAo36vXqNcT\nMBwoGTc/kpN7u1Qq2kM3CVDpGPpYj8fBsyd2hJ+ladROJx9BAd+mIXKpNU5y4CNh\nPQfD9oECgYEA6NCQjZq8z3uDycAR2bjgCVG4YD/czY776C+nU/7n035aTjZclck+\nG8bKMbujX1Xvmu62+sPJTqrneVWJnWL2afQn50Jlr1cSsppj2UP0VzEH6UgaZy4x\n0IYuUNPlkXN1W3v+neyH6I3jJHoAWCc2svkIvrFikSj2ctdiDYbL7r0CgYEA2MET\na57L3tJ6suFDBZ+DxC6UX978+DeJL41V/5Hc2WmMtqIf+NxSbd0jLVOvmpkCxN0i\nyzuh/H6TDoIN1unslfpxH7yaZy2j3lSE9p0/+QGcqKA2k+NEvCDFFJpB+qndTjMF\nCyo8fnMPh5kx2gSAlY768W4GX8ItuhKh2C0lojcCfw91yiOdIuykRxwepRDQNhBo\nXNYHZ6I+3HuOro3lX3+r5FNNSNiphHZTvRmQXEj4a/Dd6Ui9t6CBuN1V0M2ixLpE\nfGHfBuGd5p/1oKvM12zy1JOpNhej+arfPjQf3h7KjACHO2FBU8UdpvfFIkC4WemI\noAwJu4HoNnVp2BkN2n0CgYEAye8WqKzIQk7VANHcHuD9YUgD801LX/RdWm/SLsc1\neVdcQMnJ/49DPBdJLnFIqD7k1YMvZyenQhSp7Fo9intkblVkDq0nK/jZMciMFzVo\n5BMcX/zi2+RfpOTits7/qQeXpcLicARpV2Takvml9/c51BvgrgxS4+ODtlalcUCe\nTwECgYEA57k4jzoRMnT+ZcS1PU8OkGdj2CeknQLd7jyySJXqVIEQevc7v5hapY0H\nxdgbkIvrjPrI6PbsEFBQNHc2dutEz62/yLv9PMvpFDyTWNt2U5PT7O0HKA9+C4dY\nKd7+vswrcKSkejyMrAUoGKf+ZE/xRMKtqckYi1YP+Qcbdo3Tk7E=\n-----END RSA PRIVATE KEY-----\n"
      PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxR+Q3c+iBlKhcyd0mcgR\nkyHpRx8NdPW5agUeUenwrC8YyQIbshumV4w/gJZ+qGw7g3VXkXe+fAUhV9c+XiXz\ng0ouNCVbg5lT0Wr+PmkOM/bAGLHpy5pZ2RaFKzKLB1shZoMXpoR/LlK6j7mli0Ts\nWzwwq46L8CV+UiN6mnKazwF6mFyLQUaZ8qbcKHYYh500y33SmtncELlyuNPOGrmu\n3wOUjmfwfC0rTPb0XaxC2yMfMDmcfGXwYZliLgi9521P3yQm9dHjbo/ML99cYA3y\nQFP211ZXdO6esup1Z6sOsxw95t6U6AjU3cXcC03NohhSK9DmOp0aSzGdeUEdvTTk\nmwIDAQAB\n-----END PUBLIC KEY-----\n"
    depends_on:
      - postgres
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  postgres:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
  bundle:
